var searchData=
[
  ['mad',['MAD',['../group__mad.html',1,'']]],
  ['mad_28constant_29',['MAD(constant)',['../group__mad__constant.html',1,'']]],
  ['mad_28filter_29',['MAD(filter)',['../group__mad__filter.html',1,'']]],
  ['mad_28filter_2c_20constant_29',['MAD(filter, constant)',['../group__mad__filter__constant.html',1,'']]],
  ['mannwhitneyu',['mannWhitneyU',['../group__mann__whitney__u.html',1,'']]],
  ['matrix_2esc',['matrix.sc',['../group__matrix.html',1,'']]],
  ['matrixlookup',['matrixLookup',['../group__matrixlookup.html',1,'']]],
  ['matrixlookupcolumn',['matrixLookupColumn',['../group__matrixlookupcolumn.html',1,'']]],
  ['matrixlookuprow',['matrixLookupRow',['../group__matrixlookuprow.html',1,'']]],
  ['matrixmultiplication',['matrixMultiplication',['../group__matrixmultiplication.html',1,'']]],
  ['matrixmultiplication_5b_5b3_5d_5d',['matrixMultiplication[[3]]',['../group__matrixmultiplication__cube.html',1,'']]],
  ['matrixmultiplication_5b_5b2_5d_5d',['matrixMultiplication[[2]]',['../group__matrixmultiplication__mat.html',1,'']]],
  ['matrixupdate',['matrixUpdate',['../group__matrixupdate.html',1,'']]],
  ['matrixupdatecolumn',['matrixUpdateColumn',['../group__matrixupdatecolumn.html',1,'']]],
  ['matrixupdaterow',['matrixUpdateRow',['../group__matrixupdaterow.html',1,'']]],
  ['max',['max',['../group__max.html',1,'']]],
  ['max',['max',['../group__max1.html',1,'']]],
  ['max_28pointwise_29',['max(pointwise)',['../group__max2.html',1,'']]],
  ['max_28parts_29',['max(parts)',['../group__max3.html',1,'']]],
  ['maximum',['maximum',['../group__maximum.html',1,'']]],
  ['mean',['mean',['../group__mean.html',1,'']]],
  ['mean_28filter_29',['mean(filter)',['../group__mean__filter.html',1,'']]],
  ['min',['min',['../group__min.html',1,'']]],
  ['min',['min',['../group__min1.html',1,'']]],
  ['min_28pointwise_29',['min(pointwise)',['../group__min2.html',1,'']]],
  ['min_28parts_29',['min(parts)',['../group__min3.html',1,'']]],
  ['minimum',['minimum',['../group__minimum.html',1,'']]],
  ['multipletesting',['multipleTesting',['../group__multiple__testing.html',1,'']]],
  ['murmurhashervec',['murmurHasherVec',['../group__murmurhashervec.html',1,'']]],
  ['matrixmultiplication',['matrixMultiplication',['../group__shared3p__matrixmultiplication.html',1,'']]],
  ['matrixmultiplication_5b_5b3_5d_5d',['matrixMultiplication[[3]]',['../group__shared3p__matrixmultiplication__cube.html',1,'']]],
  ['matrixmultiplication_5b_5b2_5d_5d',['matrixMultiplication[[2]]',['../group__shared3p__matrixmultiplication__mat.html',1,'']]],
  ['matrixupdate',['matrixUpdate',['../group__shared3p__matrixupdate.html',1,'']]],
  ['matrixupdatecolumn',['matrixUpdateColumn',['../group__shared3p__matrixupdatecolumn.html',1,'']]],
  ['matrixupdaterow',['matrixUpdateRow',['../group__shared3p__matrixupdaterow.html',1,'']]],
  ['max',['max',['../group__shared3p__max.html',1,'']]],
  ['max_282_20vectors_29',['max(2 vectors)',['../group__shared3p__max__2.html',1,'']]],
  ['max_28parts_29',['max(parts)',['../group__shared3p__max__k.html',1,'']]],
  ['max',['max',['../group__shared3p__max__vec.html',1,'']]],
  ['min',['min',['../group__shared3p__min.html',1,'']]],
  ['min_282_20vectors_29',['min(2 vectors)',['../group__shared3p__min__2.html',1,'']]],
  ['min_28parts_29',['min(parts)',['../group__shared3p__min__k.html',1,'']]],
  ['min',['min',['../group__shared3p__min__vec.html',1,'']]]
];
