var searchData=
[
  ['pairedttest',['pairedTTest',['../group__paired__t__test.html',1,'']]],
  ['print3darray',['print3dArray',['../group__print3darray.html',1,'']]],
  ['printarray',['printArray',['../group__printarray.html',1,'']]],
  ['printmatrix',['printMatrix',['../group__printmatrix.html',1,'']]],
  ['printvector',['printVector',['../group__printvector.html',1,'']]],
  ['product',['product',['../group__product.html',1,'']]],
  ['product',['product',['../group__product1.html',1,'']]],
  ['product_28parts_29',['product(parts)',['../group__product2.html',1,'']]],
  ['publish',['publish',['../group__publish.html',1,'']]],
  ['product',['product',['../group__shared2p__product.html',1,'']]],
  ['product_28parts_29',['product(parts)',['../group__shared2p__product__k.html',1,'']]],
  ['product',['product',['../group__shared2p__product__vec.html',1,'']]],
  ['publish',['publish',['../group__shared2p__publish.html',1,'']]],
  ['parametersstandarderrors',['parametersStandardErrors',['../group__shared3p__params__stderr.html',1,'']]],
  ['pcaresult',['PCAResult',['../group__shared3p__pca__result.html',1,'']]],
  ['pow',['pow',['../group__shared3p__pow.html',1,'']]],
  ['product',['product',['../group__shared3p__product.html',1,'']]],
  ['product_28parts_29',['product(parts)',['../group__shared3p__product__k.html',1,'']]],
  ['product',['product',['../group__shared3p__product__vec.html',1,'']]],
  ['publish',['publish',['../group__shared3p__publish.html',1,'']]]
];
