var searchData=
[
  ['chisquared',['chiSquared',['../group__chisq.html',1,'']]],
  ['chisquared_28with_20codebook_29',['chiSquared(with codebook)',['../group__chisq__cb.html',1,'']]],
  ['chisquared_28goodness_20of_20fit_29',['chiSquared(goodness of fit)',['../group__chisq__goodness__of__fit.html',1,'']]],
  ['chisquared_28goodness_20of_20fit_20with_20probabilities_29',['chiSquared(goodness of fit with probabilities)',['../group__chisq__goodness__of__fit__prob.html',1,'']]],
  ['choose',['choose',['../group__choose.html',1,'']]],
  ['choose_28single_20condition_29',['choose(single condition)',['../group__choose1.html',1,'']]],
  ['choose_28multiple_20conditions_29',['choose(multiple conditions)',['../group__choose2.html',1,'']]],
  ['colsums',['colSums',['../group__colsums.html',1,'']]],
  ['combineddegreesoffreedom',['combinedDegreesOfFreedom',['../group__combined__df.html',1,'']]],
  ['contingencytable',['contingencyTable',['../group__contingency.html',1,'']]],
  ['countzeroes',['countZeroes',['../group__countzeroes.html',1,'']]],
  ['covariance',['covariance',['../group__covariance.html',1,'']]],
  ['covariance_28filter_29',['covariance(filter)',['../group__covariance__filter.html',1,'']]],
  ['crc',['CRC',['../group___c_r_c.html',1,'']]],
  ['crc_280_20initial_20hash_29',['CRC(0 initial hash)',['../group___c_r_c2.html',1,'']]],
  ['crossproduct',['crossProduct',['../group__crossproduct.html',1,'']]],
  ['crossproduct_5b_5b2_5d_5d',['crossProduct[[2]]',['../group__crossproduct__mat.html',1,'']]],
  ['crossproduct_5b_5b1_5d_5d',['crossProduct[[1]]',['../group__crossproduct__vec.html',1,'']]],
  ['cut',['cut',['../group__cut.html',1,'']]],
  ['cut_28multiple_20samples_29',['cut(multiple samples)',['../group__cut__n.html',1,'']]],
  ['cw128genkey',['cw128GenKey',['../group__cw128genkey.html',1,'']]],
  ['cw128hash',['cw128Hash',['../group__cw128hash.html',1,'']]],
  ['cw128hash_28key_29',['cw128Hash(key)',['../group__cw128hash__key.html',1,'']]],
  ['constants',['constants',['../group__hypothesis__testing__constants.html',1,'']]],
  ['choose',['choose',['../group__shared2p__choose.html',1,'']]],
  ['ceiling',['ceiling',['../group__shared3p__ceiling.html',1,'']]],
  ['cholesky',['cholesky',['../group__shared3p__cholesky.html',1,'']]],
  ['choleskyinverse',['choleskyInverse',['../group__shared3p__choleskyinverse.html',1,'']]],
  ['choose',['choose',['../group__shared3p__choose.html',1,'']]],
  ['choose_28single_20condition_29',['choose(single condition)',['../group__shared3p__choose1.html',1,'']]],
  ['choose_28multiple_20conditions_29',['choose(multiple conditions)',['../group__shared3p__choose2.html',1,'']]],
  ['colsums',['colSums',['../group__shared3p__colsums.html',1,'']]],
  ['crossproduct',['crossProduct',['../group__shared3p__crossproduct.html',1,'']]],
  ['crossproduct_5b_5b2_5d_5d',['crossProduct[[2]]',['../group__shared3p__crossproduct__mat.html',1,'']]],
  ['crossproduct_5b_5b1_5d_5d',['crossProduct[[1]]',['../group__shared3p__crossproduct__vec.html',1,'']]],
  ['constants',['constants',['../group__shared3p__glm__constants.html',1,'']]],
  ['constants',['constants',['../group__shared3p__pca__return__values.html',1,'']]],
  ['constants',['constants',['../group__shared3p__regression__method.html',1,'']]]
];
