var searchData=
[
  ['trueprefixlength',['truePrefixLength',['../group__shared2p__trueprefixlength.html',1,'']]],
  ['tdbinsertrow',['tdbInsertRow',['../group__shared3p__tdb__insert__row.html',1,'']]],
  ['tdbreadcolumn_28index_29',['tdbReadColumn(index)',['../group__shared3p__tdb__read__column__index.html',1,'']]],
  ['tdbreadcolumn_28string_29',['tdbReadColumn(string)',['../group__shared3p__tdb__read__column__string.html',1,'']]],
  ['tdbtablecreate',['tdbTableCreate',['../group__shared3p__tdb__table__create.html',1,'']]],
  ['tdbvmapaddtype',['tdbVmapAddType',['../group__shared3p__tdb__vmap__add__type.html',1,'']]],
  ['tdbvmapaddvalue_28scalar_29',['tdbVmapAddValue(scalar)',['../group__shared3p__tdb__vmap__add__value__scalar.html',1,'']]],
  ['tdbvmapaddvalue_28vector_29',['tdbVmapAddValue(vector)',['../group__shared3p__tdb__vmap__add__value__vector.html',1,'']]],
  ['tdbvmapaddvlentype',['tdbVmapAddVlenType',['../group__shared3p__tdb__vmap__add__vlen__type.html',1,'']]],
  ['tdbvmapaddvlenvalue',['tdbVmapAddVlenValue',['../group__shared3p__tdb__vmap__add__vlen__value.html',1,'']]],
  ['tdbvmapgetvalue',['tdbVmapGetValue',['../group__shared3p__tdb__vmap__get__value.html',1,'']]],
  ['tdbvmapgetvlenvalue',['tdbVmapGetVlenValue',['../group__shared3p__tdb__vmap__get__vlen__value.html',1,'']]],
  ['trueprefixlength',['truePrefixLength',['../group__shared3p__trueprefixlength.html',1,'']]],
  ['ttest',['tTest',['../group__t__test.html',1,'']]],
  ['ttest_28two_20sample_20vectors_29',['tTest(two sample vectors)',['../group__t__test__samples.html',1,'']]],
  ['table_5fdatabase_2esc',['table_database.sc',['../group__table__database.html',1,'']]],
  ['tablejoinaes128',['tableJoinAes128',['../group__tablejoinaes128.html',1,'']]],
  ['tdbcloseconnection',['tdbCloseConnection',['../group__tdb__close__connection.html',1,'']]],
  ['tdbgetcolumncount',['tdbGetColumnCount',['../group__tdb__get__column__count.html',1,'']]],
  ['tdbgetcolumnnames',['tdbGetColumnNames',['../group__tdb__get__column__names.html',1,'']]],
  ['tdbgetcolumntypes',['tdbGetColumnTypes',['../group__tdb__get__column__types.html',1,'']]],
  ['tdbgetrowcount',['tdbGetRowCount',['../group__tdb__get__row__count.html',1,'']]],
  ['tdbgettablenames',['tdbGetTableNames',['../group__tdb__get__table__names.html',1,'']]],
  ['tdbvmapgetvalue_28string_29',['tdbVmapGetValue(string)',['../group__tdb__get__value__string.html',1,'']]],
  ['tdbinsertrow',['tdbInsertRow',['../group__tdb__insert__row.html',1,'']]],
  ['tdbopenconnection',['tdbOpenConnection',['../group__tdb__open__connection.html',1,'']]],
  ['tdbreadcolumn_28index_2c_20value_20vector_29',['tdbReadColumn(index, value vector)',['../group__tdb__read__column__index__vec.html',1,'']]],
  ['tdbreadcolumn_28index_2c_20vector_20map_29',['tdbReadColumn(index, vector map)',['../group__tdb__read__column__index__vmap.html',1,'']]],
  ['tdbreadcolumn_28string_2c_20value_20vector_29',['tdbReadColumn(string, value vector)',['../group__tdb__read__column__string__vec.html',1,'']]],
  ['tdbreadcolumn_28string_2c_20vector_20map_29',['tdbReadColumn(string, vector map)',['../group__tdb__read__column__string__vmap.html',1,'']]],
  ['tdbtablecreate',['tdbTableCreate',['../group__tdb__table__create.html',1,'']]],
  ['tdbtablecreatewitherrorcode',['tdbTableCreateWithErrorCode',['../group__tdb__table__create2.html',1,'']]],
  ['tdbtabledelete',['tdbTableDelete',['../group__tdb__table__delete.html',1,'']]],
  ['tdbtableexists',['tdbTableExists',['../group__tdb__table__exists.html',1,'']]],
  ['tdbvmapaddbatch',['tdbVmapAddBatch',['../group__tdb__vmap__add__batch.html',1,'']]],
  ['tdbvmapaddindex',['tdbVmapAddIndex',['../group__tdb__vmap__add__index.html',1,'']]],
  ['tdbvmapaddstring',['tdbVmapAddString',['../group__tdb__vmap__add__string.html',1,'']]],
  ['tdbvmapaddtype',['tdbVmapAddType',['../group__tdb__vmap__add__type.html',1,'']]],
  ['tdbvmapaddvalue_28scalar_29',['tdbVmapAddValue(scalar)',['../group__tdb__vmap__add__value__scalar.html',1,'']]],
  ['tdbvmapaddvalue_28vector_29',['tdbVmapAddValue(vector)',['../group__tdb__vmap__add__value__vector.html',1,'']]],
  ['tdbvmapaddvlentype',['tdbVmapAddVlenType',['../group__tdb__vmap__add__vlen__type.html',1,'']]],
  ['tdbvmapaddvlenvalue',['tdbVmapAddVlenValue',['../group__tdb__vmap__add__vlen__value.html',1,'']]],
  ['tdbvmapclear',['tdbVmapClear',['../group__tdb__vmap__clear.html',1,'']]],
  ['tdbvmapcount',['tdbVmapCount',['../group__tdb__vmap__count.html',1,'']]],
  ['tdbvmapdelete',['tdbVmapDelete',['../group__tdb__vmap__delete.html',1,'']]],
  ['tdbvmaperase',['tdbVmapErase',['../group__tdb__vmap__erase.html',1,'']]],
  ['tdbvmapgetbatchcount',['tdbVmapGetBatchCount',['../group__tdb__vmap__get__batch__count.html',1,'']]],
  ['tdbvmapgetindex',['tdbVmapGetIndex',['../group__tdb__vmap__get__index.html',1,'']]],
  ['tdbvmapgetstring',['tdbVmapGetString',['../group__tdb__vmap__get__string.html',1,'']]],
  ['tdbvmapgettypename',['tdbVmapGetTypeName',['../group__tdb__vmap__get__type__name.html',1,'']]],
  ['tdbvmapgetvalue',['tdbVmapGetValue',['../group__tdb__vmap__get__value.html',1,'']]],
  ['tdbvmapgetvlenvalue',['tdbVmapGetVlenValue',['../group__tdb__vmap__get__vlen__value.html',1,'']]],
  ['tdbvmapnew',['tdbVmapNew',['../group__tdb__vmap__new.html',1,'']]],
  ['tdbvmapreset',['tdbVmapReset',['../group__tdb__vmap__reset.html',1,'']]],
  ['tdbvmapsetbatch',['tdbVmapSetBatch',['../group__tdb__vmap__set__batch.html',1,'']]],
  ['tdbvmapsetvalueascolumn',['tdbVmapSetValueAsColumn',['../group__tdb__vmap__set__value__as__column.html',1,'']]],
  ['tdbvmapstringvectorsize',['tdbVmapStringVectorSize',['../group__tdb__vmap__string__vector__size.html',1,'']]],
  ['tdbvmapvaluevectorsize',['tdbVmapValueVectorSize',['../group__tdb__vmap__value__vector__size.html',1,'']]],
  ['trace_2esc',['trace.sc',['../group__trace.html',1,'']]],
  ['traceload',['traceLoad',['../group__trace__load.html',1,'']]],
  ['traceload_28column_29',['traceLoad(column)',['../group__trace__load__column.html',1,'']]],
  ['traceoperation',['traceOperation',['../group__trace__operation.html',1,'']]],
  ['tracesave',['traceSave',['../group__trace__save.html',1,'']]],
  ['transpose',['transpose',['../group__transpose.html',1,'']]]
];
