var searchData=
[
  ['ceiling_867',['ceiling',['../group__shared3p__ceiling.html',1,'']]],
  ['chisquared_868',['chiSquared',['../group__chisq.html',1,'']]],
  ['chisquared_28goodness_20of_20fit_20with_20probabilities_29_869',['chiSquared(goodness of fit with probabilities)',['../group__chisq__goodness__of__fit__prob.html',1,'']]],
  ['chisquared_28goodness_20of_20fit_29_870',['chiSquared(goodness of fit)',['../group__chisq__goodness__of__fit.html',1,'']]],
  ['chisquared_28with_20codebook_29_871',['chiSquared(with codebook)',['../group__chisq__cb.html',1,'']]],
  ['cholesky_872',['cholesky',['../group__shared3p__cholesky.html',1,'']]],
  ['choleskyinverse_873',['choleskyInverse',['../group__shared3p__choleskyinverse.html',1,'']]],
  ['choose_874',['choose',['../group__choose.html',1,'(Global Namespace)'],['../group__shared2p__choose.html',1,'(Global Namespace)'],['../group__shared3p__choose.html',1,'(Global Namespace)']]],
  ['choose_28multiple_20conditions_29_875',['choose(multiple conditions)',['../group__choose2.html',1,'(Global Namespace)'],['../group__shared3p__choose2.html',1,'(Global Namespace)']]],
  ['choose_28single_20condition_29_876',['choose(single condition)',['../group__choose1.html',1,'(Global Namespace)'],['../group__shared3p__choose1.html',1,'(Global Namespace)']]],
  ['colsums_877',['colSums',['../group__colsums.html',1,'(Global Namespace)'],['../group__shared3p__colsums.html',1,'(Global Namespace)']]],
  ['combineddegreesoffreedom_878',['combinedDegreesOfFreedom',['../group__combined__df.html',1,'']]],
  ['constants_879',['constants',['../group__hypothesis__testing__constants.html',1,'(Global Namespace)'],['../group__shared3p__glm__constants.html',1,'(Global Namespace)'],['../group__shared3p__pca__return__values.html',1,'(Global Namespace)'],['../group__shared3p__regression__method.html',1,'(Global Namespace)']]],
  ['contingencytable_880',['contingencyTable',['../group__contingency.html',1,'']]],
  ['countzeroes_881',['countZeroes',['../group__countzeroes.html',1,'']]],
  ['covariance_882',['covariance',['../group__covariance.html',1,'']]],
  ['covariance_28filter_29_883',['covariance(filter)',['../group__covariance__filter.html',1,'']]],
  ['crc_884',['CRC',['../group___c_r_c.html',1,'']]],
  ['crc_280_20initial_20hash_29_885',['CRC(0 initial hash)',['../group___c_r_c2.html',1,'']]],
  ['crossproduct_886',['crossProduct',['../group__crossproduct.html',1,'(Global Namespace)'],['../group__shared3p__crossproduct.html',1,'(Global Namespace)']]],
  ['crossproduct_5b_5b1_5d_5d_887',['crossProduct[[1]]',['../group__crossproduct__vec.html',1,'(Global Namespace)'],['../group__shared3p__crossproduct__vec.html',1,'(Global Namespace)']]],
  ['crossproduct_5b_5b2_5d_5d_888',['crossProduct[[2]]',['../group__crossproduct__mat.html',1,'(Global Namespace)'],['../group__shared3p__crossproduct__mat.html',1,'(Global Namespace)']]],
  ['cut_889',['cut',['../group__cut.html',1,'']]],
  ['cut_28multiple_20samples_29_890',['cut(multiple samples)',['../group__cut__n.html',1,'']]],
  ['cw128genkey_891',['cw128GenKey',['../group__cw128genkey.html',1,'']]],
  ['cw128hash_892',['cw128Hash',['../group__cw128hash.html',1,'']]],
  ['cw128hash_28key_29_893',['cw128Hash(key)',['../group__cw128hash__key.html',1,'']]]
];
