var searchData=
[
  ['mad_963',['MAD',['../group__mad.html',1,'']]],
  ['mad_28constant_29_964',['MAD(constant)',['../group__mad__constant.html',1,'']]],
  ['mad_28filter_29_965',['MAD(filter)',['../group__mad__filter.html',1,'']]],
  ['mad_28filter_2c_20constant_29_966',['MAD(filter, constant)',['../group__mad__filter__constant.html',1,'']]],
  ['mannwhitneyu_967',['mannWhitneyU',['../group__mann__whitney__u.html',1,'']]],
  ['matrix_2esc_968',['matrix.sc',['../group__matrix.html',1,'']]],
  ['matrixlookup_969',['matrixLookup',['../group__matrixlookup.html',1,'']]],
  ['matrixlookupcolumn_970',['matrixLookupColumn',['../group__matrixlookupcolumn.html',1,'']]],
  ['matrixlookuprow_971',['matrixLookupRow',['../group__matrixlookuprow.html',1,'']]],
  ['matrixmultiplication_972',['matrixMultiplication',['../group__matrixmultiplication.html',1,'(Global Namespace)'],['../group__shared3p__matrixmultiplication.html',1,'(Global Namespace)']]],
  ['matrixmultiplication_5b_5b2_5d_5d_973',['matrixMultiplication[[2]]',['../group__matrixmultiplication__mat.html',1,'(Global Namespace)'],['../group__shared3p__matrixmultiplication__mat.html',1,'(Global Namespace)']]],
  ['matrixmultiplication_5b_5b3_5d_5d_974',['matrixMultiplication[[3]]',['../group__matrixmultiplication__cube.html',1,'(Global Namespace)'],['../group__shared3p__matrixmultiplication__cube.html',1,'(Global Namespace)']]],
  ['matrixupdate_975',['matrixUpdate',['../group__matrixupdate.html',1,'(Global Namespace)'],['../group__shared3p__matrixupdate.html',1,'(Global Namespace)']]],
  ['matrixupdatecolumn_976',['matrixUpdateColumn',['../group__matrixupdatecolumn.html',1,'(Global Namespace)'],['../group__shared3p__matrixupdatecolumn.html',1,'(Global Namespace)']]],
  ['matrixupdaterow_977',['matrixUpdateRow',['../group__matrixupdaterow.html',1,'(Global Namespace)'],['../group__shared3p__matrixupdaterow.html',1,'(Global Namespace)']]],
  ['max_978',['max',['../group__max.html',1,'(Global Namespace)'],['../group__max1.html',1,'(Global Namespace)'],['../group__shared2p__max.html',1,'(Global Namespace)'],['../group__shared2p__max__vec.html',1,'(Global Namespace)'],['../group__shared3p__max.html',1,'(Global Namespace)'],['../group__shared3p__max__vec.html',1,'(Global Namespace)']]],
  ['max_282_20vectors_29_979',['max(2 vectors)',['../group__shared2p__max__2.html',1,'(Global Namespace)'],['../group__shared3p__max__2.html',1,'(Global Namespace)']]],
  ['max_28parts_29_980',['max(parts)',['../group__max3.html',1,'(Global Namespace)'],['../group__shared2p__max__k.html',1,'(Global Namespace)'],['../group__shared3p__max__k.html',1,'(Global Namespace)']]],
  ['max_28pointwise_29_981',['max(pointwise)',['../group__max2.html',1,'']]],
  ['maximum_982',['maximum',['../group__maximum.html',1,'']]],
  ['mean_983',['mean',['../group__mean.html',1,'']]],
  ['mean_28filter_29_984',['mean(filter)',['../group__mean__filter.html',1,'']]],
  ['min_985',['min',['../group__min.html',1,'(Global Namespace)'],['../group__min1.html',1,'(Global Namespace)'],['../group__shared2p__min.html',1,'(Global Namespace)'],['../group__shared2p__min__vec.html',1,'(Global Namespace)'],['../group__shared3p__min.html',1,'(Global Namespace)'],['../group__shared3p__min__vec.html',1,'(Global Namespace)']]],
  ['min_282_20vectors_29_986',['min(2 vectors)',['../group__shared2p__min__2.html',1,'(Global Namespace)'],['../group__shared3p__min__2.html',1,'(Global Namespace)']]],
  ['min_28parts_29_987',['min(parts)',['../group__min3.html',1,'(Global Namespace)'],['../group__shared2p__min__k.html',1,'(Global Namespace)'],['../group__shared3p__min__k.html',1,'(Global Namespace)']]],
  ['min_28pointwise_29_988',['min(pointwise)',['../group__min2.html',1,'']]],
  ['minimum_989',['minimum',['../group__minimum.html',1,'']]],
  ['multipletesting_990',['multipleTesting',['../group__multiple__testing.html',1,'']]],
  ['murmurhashervec_991',['murmurHasherVec',['../group__murmurhashervec.html',1,'']]]
];
