var searchData=
[
  ['scancursor_1016',['ScanCursor',['../group___scan_cursor.html',1,'']]],
  ['selectk_1017',['selectK',['../group__selectk.html',1,'']]],
  ['selectk_5b_5b1_5d_5d_1018',['selectK[[1]]',['../group__selectk__vec.html',1,'']]],
  ['selectk_5b_5b2_5d_5d_1019',['selectK[[2]]',['../group__selectk__mat.html',1,'']]],
  ['shapesareequal_1020',['shapesAreEqual',['../group__shapesareequal.html',1,'']]],
  ['shared2p_2esc_1021',['shared2p.sc',['../group__shared2p.html',1,'']]],
  ['shared2p_5frandom_2esc_1022',['shared2p_random.sc',['../group__shared2p__random.html',1,'']]],
  ['shared3p_2esc_1023',['shared3p.sc',['../group__shared3p.html',1,'']]],
  ['shared3p_5faes_2esc_1024',['shared3p_aes.sc',['../group__shared3p__aes.html',1,'']]],
  ['shared3p_5fbl_5fstring_1025',['shared3p_bl_string',['../group__shared3p__bl__string.html',1,'']]],
  ['shared3p_5fbloom_2esc_1026',['shared3p_bloom.sc',['../group__shared3p__bloom.html',1,'']]],
  ['shared3p_5fjoin_2esc_1027',['shared3p_join.sc',['../group__shared3p__join.html',1,'']]],
  ['shared3p_5fkeydb_2esc_1028',['shared3p_keydb.sc',['../group__shared3p__keydb.html',1,'']]],
  ['shared3p_5fkl_5fstring_1029',['shared3p_kl_string',['../group__shared3p__kl__string.html',1,'']]],
  ['shared3p_5fmatrix_2esc_1030',['shared3p_matrix.sc',['../group__shared3p__matrix.html',1,'']]],
  ['shared3p_5foblivious_2esc_1031',['shared3p_oblivious.sc',['../group__shared3p__oblivious.html',1,'']]],
  ['shared3p_5fpermutation_2esc_1032',['shared3p_permutation.sc',['../group__shared3p__permutation.html',1,'']]],
  ['shared3p_5frandom_2esc_1033',['shared3p_random.sc',['../group__shared3p__random.html',1,'']]],
  ['shared3p_5fsort_2esc_1034',['shared3p_sort.sc',['../group__shared3p__sort.html',1,'']]],
  ['shared3p_5fstatistics_5fcommon_2esc_1035',['shared3p_statistics_common.sc',['../group__shared3p__statistics__common.html',1,'']]],
  ['shared3p_5fstatistics_5fdistribution_2esc_1036',['shared3p_statistics_distribution.sc',['../group__shared3p__statistics__distribution.html',1,'']]],
  ['shared3p_5fstatistics_5fglm_2esc_1037',['shared3p_statistics_glm.sc',['../group__shared3p__statistics__glm.html',1,'']]],
  ['shared3p_5fstatistics_5foutliers_2esc_1038',['shared3p_statistics_outliers.sc',['../group__shared3p__statistics__outliers.html',1,'']]],
  ['shared3p_5fstatistics_5fpca_2esc_1039',['shared3p_statistics_pca.sc',['../group__shared3p__statistics__pca.html',1,'']]],
  ['shared3p_5fstatistics_5fregression_2esc_1040',['shared3p_statistics_regression.sc',['../group__shared3p__statistics__regression.html',1,'']]],
  ['shared3p_5fstatistics_5fsummary_2esc_1041',['shared3p_statistics_summary.sc',['../group__shared3p__statistics__summary.html',1,'']]],
  ['shared3p_5fstatistics_5ftesting_2esc_1042',['shared3p_statistics_testing.sc',['../group__shared3p__statistics__testing.html',1,'']]],
  ['shared3p_5fstring_2esc_1043',['shared3p_string.sc',['../group__shared3p__string.html',1,'']]],
  ['shared3p_5ftable_5fdatabase_2esc_1044',['shared3p_table_database.sc',['../group__shared3p__table__database.html',1,'']]],
  ['shuffle_1045',['shuffle',['../group__shuffle.html',1,'(Global Namespace)'],['../group__shuffle1.html',1,'(Global Namespace)']]],
  ['shuffle_28key_29_1046',['shuffle(key)',['../group__shuffle2.html',1,'']]],
  ['shufflecolumns_1047',['shuffleColumns',['../group__shufflecols1.html',1,'']]],
  ['shufflecolumns_28key_29_1048',['shuffleColumns(key)',['../group__shufflecols2.html',1,'']]],
  ['shufflerows_1049',['shuffleRows',['../group__shufflerows1.html',1,'']]],
  ['shufflerows_28key_29_1050',['shuffleRows(key)',['../group__shufflerows2.html',1,'']]],
  ['sign_1051',['sign',['../group__shared2p__sign.html',1,'(Global Namespace)'],['../group__sign.html',1,'(Global Namespace)']]],
  ['simplelinearregression_1052',['simpleLinearRegression',['../group__shared3p__simple__linear__regression.html',1,'']]],
  ['sin_1053',['sin',['../group__shared3p__sin.html',1,'(Global Namespace)'],['../group__sin.html',1,'(Global Namespace)']]],
  ['sizeof_1054',['sizeof',['../group__sizeof.html',1,'']]],
  ['sort_1055',['sort',['../group__sort.html',1,'(Global Namespace)'],['../group__stdlib__sort.html',1,'(Global Namespace)'],['../group__stdlib__sort__simple.html',1,'(Global Namespace)']]],
  ['sort_28direction_29_1056',['sort(direction)',['../group__stdlib__sort__direction.html',1,'']]],
  ['sort_5b_5b1_5d_5d_1057',['sort[[1]]',['../group__sort__vec.html',1,'']]],
  ['sort_5b_5b2_5d_5d_1058',['sort[[2]]',['../group__sort__mat.html',1,'']]],
  ['sortingnetworksort_1059',['sortingNetworkSort',['../group__sortingnetwork.html',1,'']]],
  ['sortingnetworksort_5b_5b1_5d_5d_1060',['sortingNetworkSort[[1]]',['../group__sortingnetwork__vec.html',1,'']]],
  ['sortingnetworksort_5b_5b2_5d_5d_281_20column_29_1061',['sortingNetworkSort[[2]](1 column)',['../group__sortingnetwork__mat.html',1,'']]],
  ['sortingnetworksort_5b_5b2_5d_5d_282_20columns_29_1062',['sortingNetworkSort[[2]](2 columns)',['../group__sortingnetwork__mat2.html',1,'']]],
  ['sortingnetworksort_5b_5b2_5d_5d_283_20columns_29_1063',['sortingNetworkSort[[2]](3 columns)',['../group__sortingnetwork__mat3.html',1,'']]],
  ['sqrt_1064',['sqrt',['../group__shared3p__sqrt.html',1,'(Global Namespace)'],['../group__sqrt.html',1,'(Global Namespace)']]],
  ['standarddev_1065',['standardDev',['../group__standard__dev.html',1,'']]],
  ['standarddev_28filter_29_1066',['standardDev(filter)',['../group__standard__dev__filter.html',1,'']]],
  ['startsection_1067',['startSection',['../group__profiling__start__section.html',1,'']]],
  ['stdlib_2esc_1068',['stdlib.sc',['../group__stdlib.html',1,'']]],
  ['substring_1069',['substring',['../group__substring.html',1,'']]],
  ['sum_1070',['sum',['../group__shared2p__sum.html',1,'(Global Namespace)'],['../group__shared2p__sum__vec.html',1,'(Global Namespace)'],['../group__shared3p__sum.html',1,'(Global Namespace)'],['../group__shared3p__sum__vec.html',1,'(Global Namespace)'],['../group__sum.html',1,'(Global Namespace)'],['../group__sum1.html',1,'(Global Namespace)']]],
  ['sum_28parts_29_1071',['sum(parts)',['../group__shared2p__sum__k.html',1,'(Global Namespace)'],['../group__shared3p__sum__k.html',1,'(Global Namespace)'],['../group__sum2.html',1,'(Global Namespace)']]]
];
