var searchData=
[
  ['keydb_2esc',['keydb.sc',['../group__keydb.html',1,'']]],
  ['keydb_5fclean',['Keydb_clean',['../group__keydb__clean.html',1,'']]],
  ['keydb_5fconnect_28string_29',['keydb_connect(string)',['../group__keydb__connect.html',1,'']]],
  ['keydb_5fdel_28string_29',['keydb_del(string)',['../group__keydb__del.html',1,'']]],
  ['keydb_5fdisconnect_28void_29',['keydb_disconnect(void)',['../group__keydb__disconnect.html',1,'']]],
  ['keydb_5fget_28string_29',['keydb_get(string)',['../group__keydb__get.html',1,'']]],
  ['keydb_5fscan_28string_29',['keydb_scan(string)',['../group__keydb__scan.html',1,'']]],
  ['keydb_5fscan_5fnext_28cursor_29',['keydb_scan_next(cursor)',['../group__keydb__scan__next.html',1,'']]],
  ['keydb_5fset_28string_2c_20value_29',['keydb_set(string, value)',['../group__keydb__set.html',1,'']]],
  ['kl_5fstr',['kl_str',['../group__kl__str.html',1,'']]],
  ['kl_5fstrcat',['kl_strCat',['../group__kl__strcat.html',1,'']]],
  ['kl_5fstrcontains',['kl_strContains',['../group__kl__strcontains.html',1,'']]],
  ['kl_5fstrdeclassify',['kl_strDeclassify',['../group__kl__strdeclassify.html',1,'']]],
  ['kl_5fstreqprefixes',['kl_strEqPrefixes',['../group__kl__streqprefixes.html',1,'']]],
  ['kl_5fstrequals',['kl_strEquals',['../group__kl__strequals.html',1,'']]],
  ['kl_5fstrhamming',['kl_strHamming',['../group__kl__strhamming.html',1,'']]],
  ['kl_5fstrindexof',['kl_strIndexOf',['../group__kl__strindexof.html',1,'']]],
  ['kl_5fstrislessthan',['kl_strIsLessThan',['../group__kl__strislessthan.html',1,'']]],
  ['kl_5fstrlength',['kl_strLength',['../group__kl__strlength.html',1,'']]],
  ['kl_5fstrlevenshtein',['kl_strLevenshtein',['../group__kl__strlevenshtein.html',1,'']]],
  ['keydb_5fget',['keydb_get',['../group__shared3p__keydb__get.html',1,'']]],
  ['keydb_5fset',['keydb_set',['../group__shared3p__keydb__set.html',1,'']]]
];
